### ISSUE TITLE
在文章内容区的drawer中没有其他主栏目项目

### ISSUE THREAD

**Issue by zhudhjen** [QSCTech/freshman-mobile#1]
例如在军训区不能直接切换到生活区，诸如此类

**Comment by Senorsen** [comment]
噗，手机空间略小，不知道该把按钮放在哪……

于 2014年07月28日 14:59, Dinghan Zhu 写道:

> 例如在军训区不能直接切换到生活区，诸如此类
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/QSCTech/freshman-mobile/issues/1.

## 

 From   Senorsen - 张森
E-mail:     sen@senorsen.com mailto:sen@senorsen.com
URL:    http://www.senorsen.com http://www.senorsen.com

**Comment by zhudhjen** [comment]
唔，Android的话侧边栏是可以单独滚动的

**Comment by Senorsen** [comment]
恩……噗……我可能是因为懒- -。。我明天、后天或大后天会试试的～

于 2014年07月28日 22:13, Dinghan Zhu 写道:

> 唔，Android的话侧边栏是可以单独滚动的
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/QSCTech/freshman-mobile/issues/1#issuecomment-50343259.

## 

 From   Senorsen - 张森
E-mail:     sen@senorsen.com mailto:sen@senorsen.com
URL:    http://www.senorsen.com http://www.senorsen.com
